version: 2.1
jobs:
  build:
    working_directory: ~/summarizer
    docker:
      - image: cimg/python:3.6.9 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: Upgrading pip
          command: pip install --upgrade pip
      - run:
          name: Installing python dependencies
          command: pip install -r requirements.txt --find-links https://download.pytorch.org/whl/torch_stable.html
      - run:
          name: Checking type consistency
          command: mypy src
      - run:
          name: Checking code format
          command: flake8
      - run:
          name: Loading ML models
          command: python src/load_models.py
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/summarizer
    docker:
      - image: cimg/python:3.6.9
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Upgrading pip
          command: pip install --upgrade pip
      - run:
          name: Installing python dependencies
          command: pip install -r requirements.txt --find-links https://download.pytorch.org/whl/torch_stable.html
      - run:
          name: Running tests
          command: pytest -W ignore::DeprecationWarning
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build